source:
  language:
    [
      "af",
      "ar",
      "be",
      "bg",
      "bxr",
      "ca",
      "cop",
      "cs",
      "cu",
      "cy",
      "da",
      "de",
      "el",
      "en",
      "es",
      "et",
      "eu",
      "fa",
      "fi",
      "fo",
      "fr",
      "fro",
      "ga",
      "gd",
      "gl",
      "got",
      "grc",
      "gv",
      "hbo",
      "he",
      "hi",
      "hr",
      "hsb",
      "hu",
      "hy",
      "hyw",
      "id",
      "is",
      "it",
      "ja",
      "kk",
      "kmr",
      "ko",
      "koi",
      "kpv",
      "ky",
      "la",
      "lij",
      "lt",
      "lv",
      "lzh",
      "mdf",
      "mr",
      "mt",
      "myv",
      "nl",
      "no",
      "olo",
      "orv",
      "pcm",
      "pl",
      "pt",
      "qaf",
      "qpm",
      "qtd",
      "ro",
      "ru",
      "sa",
      "sk",
      "sl",
      "sme",
      "sms",
      "sr",
      "sv",
      "ta",
      "te",
      "tr",
      "ug",
      "uk",
      "ur",
      "vi",
      "wo",
      "zh",
    ]

target:
  task_format: "{task_name}-{language}"

  token-classification:
    udpos213: {
        dataset: "./datasets/udpos213|{language}", # dataset|subset
        language:
          [
            "af",
            "ar",
            "be",
            "bg",
            "bxr",
            "ca",
            "cop",
            "cs",
            "cu",
            "cy",
            "da",
            "de",
            "el",
            "en",
            "es",
            "et",
            "eu",
            "fa",
            "fi",
            "fo",
            "fr",
            "fro",
            "ga",
            "gd",
            "gl",
            "got",
            "grc",
            "gv",
            "hbo",
            "he",
            "hi",
            "hr",
            "hsb",
            "hu",
            "hy",
            "hyw",
            "id",
            "is",
            "it",
            "ja",
            "kk",
            "kmr",
            "ko",
            "koi",
            "kpv",
            "ky",
            "la",
            "lij",
            "lt",
            "lv",
            "lzh",
            "mdf",
            "mr",
            "mt",
            "myv",
            "nl",
            "no",
            "olo",
            "orv",
            "pcm",
            "pl",
            "pt",
            "qaf",
            "qpm",
            "qtd",
            "ro",
            "ru",
            "sa",
            "sk",
            "sl",
            "sme",
            "sms",
            "sr",
            "sv",
            "ta",
            "te",
            "tr",
            "ug",
            "uk",
            "ur",
            "vi",
            "wo",
            "zh",
          ]
      }

model:
  type:
    ft: {}

  config:
    xlm-roberta-base: [ft]